# Generated by Django 4.2.6 on 2023-10-19 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='no',
        ),
    ]
